### ISSUE TITLE
Point subdomain to the latest working version of the app

### ISSUE THREAD

**Issue by juan-fintech** [tomyo/birm#10]
We need to think if we want to have 2 (stable + experimental) or just one version.

Potential subdomains:
app.birm.xyz
demo.birm.xyz
stage.birm.xyz

**Comment by tomyo** [comment]
app.birm.xyz -> master branch
demo.birm.xyz -> develop branch
For now looks like enough

**Comment by tomyo** [comment]
Leaving open, for @juan-fintech to review and close.

**Comment by tomyo** [comment]
Juan, si le dabas close al issue, ya se movía solo a Done, le doy close ahora yo.
![image](https://user-images.githubusercontent.com/708569/83066660-af374f00-a065-11ea-896e-b0d6c9a4d6ce.png)
