### ISSUE TITLE
Point DNS to Yandex

### ISSUE THREAD

**Issue by juan-fintech** [tomyo/birm#12]
TXT
@
yandex-verification: 99b2d7de0b0805a2

MX
10
@
mx.yandex.net.

**Comment by tomyo** [comment]
Listo, confirmame si en Yandex están bien.

**Comment by juan-fintech** [comment]
@tomyo .

Yeah. Me olvidé de poner la firmita para que no lo ponga como Spam. Abro otro ticke', abro.
