### ISSUE TITLE
Create Landing Page to put under birm.xyz

### ISSUE THREAD

**Issue by juan-fintech** [tomyo/birm#9]
@juan-fintech to design wireframe (high level design + content).

@tomyo to find template + deploy content to birm.xyz

**Comment by tomyo** [comment]
Is this a showcase of birm?

**Comment by tomyo** [comment]
This one looks nice:
https://github.com/cruip/open-react-template

**Comment by juan-fintech** [comment]
https://open.cruip.com/

**Comment by tomyo** [comment]
![image](https://user-images.githubusercontent.com/708569/81506985-53956380-92fa-11ea-9fb0-163f3e63b84c.png)

acá va el texto que quiero
